{"name": "Проверка оформления заказа залогиненным пользователем", "status": "broken", "statusDetails": {"message": "UnboundLocalError: cannot access local variable 'access_token' where it is not associated with a value", "trace": "@pytest.fixture\n    def email_password():\n>       email_password, access_token = create_new_user_and_return_user_data()\n\nconftest.py:34: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\n    @allure.step('Регистрация пользователя и сохранение его данных.')\n    def create_new_user_and_return_user_data():\n        email_password = {}\n        payload = generate_full_data_for_user_creation()\n        user_methods = UserMethods()\n        response = user_methods.create_user(payload)\n        if response.status_code == 200:\n            access_token = response.json()[\"accessToken\"]\n            email_password[\"email\"] = payload[\"email\"]\n            email_password[\"password\"] = payload[\"password\"]\n>       return email_password, access_token\nE       UnboundLocalError: cannot access local variable 'access_token' where it is not associated with a value\n\nhelpers.py:54: UnboundLocalError"}, "parameters": [{"name": "driver", "value": "'chrome'"}], "start": 1732720613098, "stop": 1732720613098, "uuid": "f3d7c65f-3fab-4d45-b93e-cc309b8605fd", "historyId": "bc414ebeae4932aee87b9f6ed1632b6b", "testCaseId": "0d82315d8c88ff7669d32f8e814cd0bf", "fullName": "tests.test_main_functional.TestMainFunctional#test_make_order_by_authorized_user", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_main_functional"}, {"name": "subSuite", "value": "TestMainFunctional"}, {"name": "host", "value": "mbp-dchernukha-OZON-C02F51KFML85"}, {"name": "thread", "value": "57255-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_main_functional"}]}